Update .zshrc

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -20,13 +20,13 @@
 source "$HOME/.shell/utils.sh"
 source "$HOME/.shell/plugins/sleep.sh"
 
-# Wait for dependencies to be installed 
-# This makes sure that the shell does not spawan multiple times 
-# if the dependencies are not installed 
+# Wait for dependencies to be installed
+# This makes sure that the shell does not spawan multiple times
+# if the dependencies are not installed
 wait_for_dependencies_interactive() {
     if ! ensure_installed "git" "fzf" "curl"; then
-        echo "Please install the above programs before continuing."
-        echo "Do you want to enter a POSIX shell to install them? [Y/n]"
+        echo -e "\033[1;33m Please install the above programs before continuing."
+        echo -e "\033[0;36m Do you want to enter a POSIX shell to install them? [Y/n]"
         read -r answer
         if [ "$answer" != "n" ]; then
             # spawn a posix shell and wait for it to exit
@@ -34,7 +34,7 @@ wait_for_dependencies_interactive() {
             # Check if the dependencies are installed
             wait_for_dependencies
         else
-            echo "Aborting..."
+            echo -e "\033[0;31m Aborting..."
             return 1
         fi
     fi
@@ -55,7 +55,7 @@ wait_for_dependencies_interactive() {
     fi
 
     if [ "$start_shell" -eq 0 ]; then
-        echo "Please install the above programs before continuing."
+        echo -e "\033[0;31m Please install the above programs before continuing."
         return 1
     fi
 ) || return 1
@@ -99,8 +99,9 @@ bindkey -v
 fix_ssh_permissions
 
 # Start ssh-agent, supress output
-eval "$(ssh-agent -s  | sed 's/^echo/#echo/')"
-
+if ! is_wsl; then
+    eval "$(ssh-agent -s | sed 's/^echo/#echo/')"
+fi
 
 # SSH Add on darwin
 # https://superuser.com/a/1721414
@@ -108,21 +109,19 @@ if is_darwin; then
     # Load ssh keys into ssh-agent, supress output
     ssh-add --apple-load-keychain -q
 elif is_wsl; then
-    eval "$(keychain --quiet --eval --agents ssh)"
+    eval "$(keychain --eval --agents ssh)"
 fi
 
 if ! ssh-add -l >/dev/null 2>&1; then
     public_key_count="$(\find $HOME/.ssh/ -type f \( -name "*.pub" \) | wc -l)"
     if [ "$public_key_count" -gt 0 ]; then
-        echo "SSH keys not added, adding..."
-
         if is_darwin; then
             # Add keys
             ssh-add --apple-use-keychain
             # Refresh keychain
             ssh-add --apple-load-keychain -q
         else
-            echo "Please run `ssh-add` to add your ssh keys"
+            echo -e "\033[1;33m Please run 'ssh-add <optional-path-to-key>' to add your ssh keys"
         fi
     fi
 fi
@@ -172,7 +171,7 @@ if is_installed "nvim"; then
     export EDITOR="nvim"
     export VISUAL="$EDITOR"
 else
-    echo "nvim not installed, using vim"
+    echo -e "\033[1;33m nvim not installed, using vim"
     export EDITOR="vim"
     export VISUAL="$EDITOR"
 fi
@@ -214,7 +213,6 @@ export GPG_TTY=$(tty)
 
 # Add homebrew to fpath
 fpath=("$HOMEBREW_PREFIX/share/zsh/site-functions" $fpath)
-
 
 add_multiple_to_path "$HOME/.local/bin" "$HOME/.rd/bin" "$HOME/sdk" "$HOME/go/bin"
 
@@ -261,7 +259,7 @@ if [ -f "$HOME/.dotbare/dotbare.plugin.zsh" ]; then
 fi
 
 if ! is_installed "dotbare"; then
-    echo "Installing dotbare via git..."
+    echo -e "\033[1;33m Installing dotbare via git..."
     git clone https://github.com/kazhala/dotbare.git "$HOME/.dotbare"
     source "$HOME/.dotbare/dotbare.plugin.zsh"
 fi
@@ -272,7 +270,7 @@ alias dot="dotbare"
 ##################################################
 
 if ! is_installed "pfetch-with-kitties"; then
-    echo "Installing pfetch-with-kitties..."
+    echo -e "\033[1;33m Installing pfetch-with-kitties..."
     mkdir -p "$HOME/.local/bin"
     add_to_path "$HOME/.local/bin"
     # I use my own fork, becaus I audited it
@@ -282,10 +280,10 @@ fi
 
 if is_installed "pfetch-with-kitties"; then
     if is_wsl; then
-        echo ""
+        echo -e "\n"
         HOSTNAME="wsl" PF_INFO="ascii title os uptime memory" PF_ASCII="Catppuccin" pfetch-with-kitties
     else
-        echo ""
+        echo -e "\n"
         HOSTNAME="mac" PF_INFO="ascii title os uptime memory" PF_ASCII="Catppuccin" pfetch-with-kitties
     fi
 fi
@@ -371,7 +369,7 @@ if is_installed "zplug"; then # damn zplug, the author didn't even archive the r
     if ! zplug check --verbose; then
         printf "Install? [y/N]: "
         if read -q; then
-            echo
+            echo -e "\n"
             zplug install
         fi
     fi
@@ -379,7 +377,7 @@ if is_installed "zplug"; then # damn zplug, the author didn't even archive the r
     # Then, source plugins and add commands to $PATH
     zplug load
 else
-    echo "Please install zplug to use plugins."
+    echo -e "\033[1;33m Please install zplug to use plugins."
 fi
 
 # load completions
